### ISSUE TITLE
Convivial-template repository isn't public, it seems

### ISSUE THREAD

**Issue by miloskroulik** [morpht/convivial#8]
I'd like to explore this new version of Convivial more, but https://github.com/morpht/convivial-template isn't accessible.Is this meant to be a public project?

**Comment by naveenvalecha** [comment]
@miloskroulik Here's the project https://github.com/morpht/convivial-recommended to create a new project

**Comment by miloskroulik** [comment]
Thanks, I was referring to the readme, where https://github.com/morpht/convivial-template is mentioned.

**Comment by naveenvalecha** [comment]
we will update it.

**Comment by naveenvalecha** [comment]
This is fixed in https://github.com/morpht/convivial/pull/11
